name: Metrics
on:
  # Se actualiza cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente
  workflow_dispatch:
  # Se ejecuta al subir cambios a la rama principal
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu token guardado en Secrets
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuración del plugin Habits
          base: "" # Desactiva el resto de stats básicas si solo quieres Habits
          plugin_habits: yes
          plugin_habits_days: 14      # Días de historial a analizar
          plugin_habits_facts: yes    # Muestra hechos (ej. "el más activo los viernes")
          plugin_habits_charts: yes   # Muestra gráficos de barras
          config_timezone: Europe/Madrid # Ajusta a tu zona horaria
